### PR TITLE
Average circular angles tests

### PR DESCRIPTION
**Pull request by Crashthatch**
Add unit tests for #18 / #19.

### CODE REVIEW

**Comment by david-rhodes** [comment]
Does this replace #19?

**Comment by Crashthatch** [comment]
Yes. I did two PRs in case you wanted the fix but not the test (not sure if I used the right testing framework, format etc)

**Comment by wilhelmberg** [comment]
@Crashthatch

> Yes. I did two PRs in case you wanted the fix but not the test

No PR is complete without tests 😏 
Yes, tests are **very** welcome - thanks.


> not sure if I used the right testing framework, format

 We are using the `nunit` test framework that comes with Unity so that the tests show up in Unity Editor `Window -> Test Runner`.

Examples of other tests:
https://github.com/mapbox/mapbox-unity-sdk/tree/develop/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Tests/UnitTests/Editor

Would you mind changing yours form the VS testing tools to nunit and make them show up in Unity Edtior?
Let me know if you need any help with that.

**Comment by wilhelmberg** [comment]
Going to merge #19 (without tests) and port test from this PR manually.

**Comment by wilhelmberg** [comment]
Merged #19 and ported tests with #34

**Pull request closed without merging**
